### ISSUE TITLE
LoadingIndicator freezes

### ISSUE THREAD

**Issue by hebrao** [zhaoyipeng/FMXComponents#12]
I'm trying to create a "loading screen". This will be open while some requests to webservices are processing.
Ex:
Step 1 -> Show Form with LoadingIndicator...
Step 2 -> RestRequest.Execute... (this takes 10 seconds to finish)...
Step 3 -> Close Form with LoadingIndicator...

But, when i open form (Step 1), LoadingIndicator stay freeze. It doesn't spin... 
Could you, please, help me to solve this?

**Comment by aso14** [comment]
Hey ! Can i see your code ?

**Comment by hebrao** [comment]
try
Frm_Loading.show;
Request_dashboard := TRESTRequest.Create();
Request_dashboard.Params.Clear;
Request_dashboard.AddParameter('user_id', '12345', TRESTRequestParameterKind.pkGETorPOST);
Request_dashboard.Execute;

finally
Frm_Loading.close;
end;

Inside Frm_Loading there's no code. Only drag and drop FMXLoadingIndicator...

**Comment by Spelt** [comment]
This is a classic one. You freeze the ui thread while doing the request. 

Its a very common mistake.   You can read about it here: https://stackoverflow.com/questions/46063689/delphi-threading-with-trestrequest

There is also a solution.

**Comment by aso14** [comment]
You can use a Parallel Programming  Library to excute the step 2  !

**Comment by loko789** [comment]
Try to put the request in a Thread like this:
```
 Frm_Loading.show;   //GUI Thread
    TThread.CreateAnonymousThread(
      procedure
      begin
        try   //Request Thread
          Request_dashboard := TRESTRequest.Create();
          Request_dashboard.Params.Clear;
          Request_dashboard.AddParameter('user_id', '12345', TRESTRequestParameterKind.pkGETorPOST);
          Request_dashboard.Execute;
        finally
          TThread.Synchronize(nil,
            procedure
            begin
              Frm_Loading.close; //Synchronize the form close after the Request
            end);

        end).Start;

      end;
```
