### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jkour** [zhaoyipeng/FMXComponents#2]
Hi,
great components.

Under what license do you release them?

Can they be used in commercial applications?

Thanks

**Comment by zhaoyipeng** [comment]
you can use in commercial application

**Comment by zhaoyipeng** [comment]
I hope that as many people as possible can benefit from this project, but I don't know which license is the best choice, I just choose Apache License, Version 2.0, can anybody give me some advice?

**Comment by jkour** [comment]
I usually go for the MIT license but I am not sure what's the difference with Apache. With MIT, the code can be used in any type of applications as long as they mention the original author.

See this page: https://choosealicense.com

**Comment by zhaoyipeng** [comment]
The license changed to MIT License
