### ISSUE TITLE
Loading Indicators and Threads

### ISSUE THREAD

**Issue by jkour** [zhaoyipeng/FMXComponents#3]
Hi,
when I use the loading indicators in apps with parallel jobs, the animation in the indicators stalls until the other jobs finish. 

I think the repaint should be done in a thread to avoid this. 

Can you have a look at it?

Thanks
John

**Comment by zhaoyipeng** [comment]
can you provide your demo code?

**Comment by jkour** [comment]
Can't reproduce it in a demo project. But I get it in my app. I will investigate and see if there is something else wrong and not the animation
