### ISSUE TITLE
Add and change something in FMX.ImageSlider

### ISSUE THREAD

**Issue by loko789** [zhaoyipeng/FMXComponents#8]
**Change**:
- MouseUp
- SetActivePage

**Add**
- MoveToActivePage

See the comments, what I have changed. If it's okay for you, then you can add this to your code.

[FMX.ImageSlider.zip](https://github.com/zhaoyipeng/FMXComponents/files/1659672/FMX.ImageSlider.zip)

**Comment by zhaoyipeng** [comment]
Thanks a lot, I can't use computer this week, I will test your code next week.

**Comment by zhaoyipeng** [comment]
already merged your code, thanks.
